print("DESERT RECIPE")
print()
print("INGREDIENTS")
firstIn = input ("Name first ingredient: ")
secondIn = input("Name second ingredient: ")
thirdIn = input("Name third ingredient: ")
fourthIn = input("Name fourth ingredient: ")
fifthIn = input("Name fifth ingredient: ")
print()
print("Time: 1 hour")
print("Steps")
print("First step is to take", firstIn, "and mix it with", secondIn, ".Then you add", thirdIn, "and mix all these togehter. After you have done this step, you can put the mix in fridge for 30min. After you take it out, you can glaze with", fourthIn, "and", fifthIn, ".")
print()
print("Enjoy ur meal!")